# Generated by Django 4.0.3 on 2022-03-31 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas'), ('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('masyarakat', 'Masyarakat')], max_length=30)),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id_alat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_alat', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(max_length=1000)),
                ('gambar_alat', models.ImageField(upload_to='gambar_alat/')),
                ('status_alat', models.CharField(default='tersedia', max_length=50)),
                ('kategori_alat', models.CharField(choices=[('auxiliary instrument', 'Auxiliary Instrument'), ('instrumen utama', 'Instrumen Utama'), ('obat-obatan', 'Obat-Obatan'), ('atk', 'ATK'), ('perawatan', 'Perawatan'), ('lain-lain', 'Lain-Lain')], max_length=80)),
                ('lokasi_alat', models.CharField(max_length=200)),
                ('kondisi_alat', models.CharField(choices=[('B', 'Baik'), ('RS', 'Rusak Sebagian'), ('RT', 'Rusak Total')], max_length=200)),
                ('tanggal_masuk', models.DateTimeField()),
                ('keterangan', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi_unit_institusi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('NRK_NIK_NIP_NIM', models.CharField(max_length=30)),
                ('KTP_KTM', models.ImageField(upload_to='ktp_ktm/')),
                ('status_verifikasi', models.CharField(choices=[('1', 'Sudah Terverifikasi'), ('0', 'Belum Terverifikasi')], default='0', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateTimeField()),
                ('tanggal_pengembalian', models.DateTimeField()),
                ('tanggal_update_data', models.DateTimeField(auto_now=True)),
                ('status_order', models.CharField(default='peminjaman', max_length=50)),
                ('alasan_meminjam', models.TextField(max_length=1000)),
                ('keterangan_ditolak', models.TextField(blank=True, max_length=1000)),
                ('catatan_kelengkapan_alat', models.TextField(blank=True, max_length=2000)),
                ('id_alat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sirius_api.alat')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(max_length=2000)),
                ('foto_catatan_penggunaan', models.ImageField(upload_to='foto_catatan_penggunaan/')),
                ('tanggal_pembuatan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirius_api.orderlog')),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(max_length=200)),
                ('alamat_instansi', models.CharField(max_length=200)),
                ('kontak_instansi', models.CharField(max_length=200)),
                ('logo_instansi', models.ImageField(upload_to='logo_instansi/')),
                ('id_alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirius_api.alat')),
            ],
        ),
    ]
