# Generated by Django 4.0.3 on 2022-03-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercore',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercore',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
