# Generated by Django 4.0.3 on 2022-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0003_alter_usercore_profile_pic_alter_userprofile_ktp_ktm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='tanggal_peminjaman',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='tanggal_pengembalian',
            field=models.DateTimeField(blank=True),
        ),
    ]
