# Generated by Django 4.0.3 on 2022-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0004_alter_orderlog_tanggal_peminjaman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='token_order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
