# Generated by Django 4.0.3 on 2022-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0005_orderlog_token_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='KTP_KTM',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
