# Generated by Django 4.0.3 on 2022-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0006_alter_usercore_profile_pic_alter_userprofile_ktp_ktm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='KTP_KTM',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
