# Generated by Django 4.0.3 on 2022-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0007_alter_usercore_profile_pic_alter_userprofile_ktp_ktm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instansi',
            name='id_alat',
        ),
        migrations.AddField(
            model_name='alat',
            name='instansi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sirius_api.instansi'),
        ),
    ]
