# Generated by Django 4.0.3 on 2022-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0009_alter_usercore_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='bisa_dipinjam',
            field=models.CharField(blank=True, choices=[('1', 'Bisa'), (0, 'Tidak Bisa')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='alat',
            name='level_peminjam',
            field=models.CharField(blank=True, choices=[('1', 'Umum - Mahasiswa - Dosen'), ('2', 'Mahasiswa - Dosen'), ('3', 'Dosen')], default=1, max_length=2),
        ),
    ]
