# Generated by Django 4.0.3 on 2022-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_api', '0010_alat_bisa_dipinjam_alat_level_peminjam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alat',
            name='gambar_alat',
            field=models.ImageField(blank=True, upload_to='gambar_alat/'),
        ),
    ]
